export const theme = {
  colors: {
    background: '#F8F2ED',
    page: '#FFFDFB',
    surface: '#FFFFFF',
    surfaceSoft: '#FFF4EA',
    border: '#F1DED0',
    textPrimary: '#1E1A17',
    textSecondary: '#5E5044',
    textMuted: '#8E7F73',
    accent: '#FF7A1A',
    accentDeep: '#E86509',
    accentSoft: '#FFE5D1',
    icon: '#3B312B',
    success: '#1FA971',
    warning: '#FF8A3D',
    tabBar: '#FFF7F0',
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 20,
    xl: 28,
    round: 999,
  },
  spacing: {
    xxs: 4,
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 30,
  },
  typography: {
    brand: 'Audiowide',
    body: 'Manrope',
    bodySemi: 'Manrope-SemiBold',
    bodyBold: 'Manrope-Bold',
    sizeXs: 11,
    sizeSm: 13,
    sizeMd: 15,
    sizeLg: 18,
    sizeXl: 28,
  },
} as const;
